# -*- coding: utf-8 -*-
"""Node_Project_2.pynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/gist/brendan-bennett/a7eba85df98d404b49b61e6f33fb4871/node_project_2-pynb.ipynb
"""

import numpy as np 
import pandas as pd
import plotly 
import plotly.express as px
from plotly.subplots import make_subplots
import plotly.graph_objects as go

df = pd.read_csv('crime_and_incarceration_by_state.csv')

prisoners_by_year = df['prisoner_count'].groupby(df['year']).sum().reset_index()
crimes_by_year = df['violent_crime_total'].groupby(df['year']).sum().reset_index()
state_population_by_year = df['state_population'].groupby(df['year']).sum().reset_index()

prisoners = prisoners_by_year['prisoner_count'].tolist()
crimes = crimes_by_year['violent_crime_total'].tolist()
population = state_population_by_year['state_population'].tolist()
years = prisoners_by_year['year'].tolist()

fig = make_subplots(rows=3, cols=1, 
                    shared_xaxes=True, 
                    vertical_spacing=0.02)

fig.add_trace(go.Scatter(x=years, y=population),
              row=3, col=1)

fig.add_trace(go.Scatter(x=years, y=crimes),
              row=2, col=1)

fig.add_trace(go.Scatter(x=years, y=prisoners),
              row=1, col=1)

fig.update_layout(height=600, width=600,
                  title_text="Incarcerated Populaion vs. Crime Rates vs. Population Growth")
fig.update_yaxes(title_text="Incarcerated Pop.", row=1, col=1)
fig.update_yaxes(title_text="Crimes Committed", row=2, col=1)
fig.update_yaxes(title_text="Total Pop.", row=3, col=1)

fig.update_xaxes(title_text="Year", col=1, row=3)

fig.show()